DROP TABLE IF EXISTS TBL_USER_GROUP;

CREATE TABLE TBL_USER_GROUP (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

INSERT INTO TBL_USER_GROUP (ID, NAME) VALUES
  (1, 'Group1'), (2, 'Group2'), (3, 'Group3');