---
swagger: "2.0"
info:
  description: shoppinglist REST API definition
  version: 1.0.0
  title: shoppinglist
basePath: /api
schemes:
- http

tags:
- name: ShoppingList
  description: The ShoppingList resource, accessed by its ID

paths:
  /shoppingList:
    get:
      tags:
      - ShoppingList
      description: Retrieves a list of the resource ShoppingList filtered by query string.
      operationId: findShoppingList
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: filter
        type: string
        required: false
        description: The filter criteria for retrieving the list
      - in: query
        name: startIndex
        type: integer
        format: int32
        required: false
        description: The start index of the first element to return (page start)
      - in: query
        name: pageSize
        type: integer
        format: int32
        required: false
        description: Maximum number of items to return in requested page.  If the list is exausted, less elements will be returned.
      responses:
        200:
          description: requested page of items matching criteria.
          schema:
            type: array
            items:
              $ref: "#/definitions/ShoppingList"

    post:
      tags:
      - ShoppingList
      description: Insert a new instance of the resource ShoppingList.
      operationId: createShoppingList
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: shoppingList
        description: The entity data to update
        required: true
        schema:
          $ref: "#/definitions/ShoppingList"
      responses:
        201:
          description: Created ShoppingList resource.
          schema:
            $ref: "#/definitions/ShoppingList"
        409:
          description: Entity with same ID already exists.
              
  /shoppingList/{id}:
    get:
      tags:
      - ShoppingList
      description: Retrieves an instance of the resource ShoppingList, having the specified id.
      operationId: getShoppingList
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: ID of the requested ShoppingList instance
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful response, with a representation of the ShoppingList resource.
          schema:
            $ref: "#/definitions/ShoppingList"
          examples:
            application/json :
              {
                id : 1234,
                name : Weekly
              }
        404:
          description: The requested ShoppingList resource instance was not found.

    post:
      tags:
      - ShoppingList
      description: Updates an existing instance of the resource ShoppingList, having the specified id.
      operationId: updateShoppingList
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: ID of the ShoppingList instance to be updated
        required: true
        type: integer
        format: int64
      - in: body
        name: shoppingList
        description: The entity data to update
        required: true
        schema:
          $ref: "#/definitions/ShoppingList"
      responses:
        200:
          description: Successful response, with a representation of the ShoppingList resource.
          schema:
            $ref: "#/definitions/ShoppingList"
        404:
          description: The requested ShoppingList resource instance was not found.
     
definitions:
  ShoppingList:
    type: object
    description: An individual ShoppingList resource instance.
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
