DROP TABLE IF EXISTS ENTITY1;

CREATE TABLE ENTITY1 (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

INSERT INTO ENTITY1 (ID, NAME) VALUES
  (1, 'Entity1'), (2, 'Instance2'), (3, 'Entity3');