---
swagger: "2.0"
info:
  description: usergroup REST API definition
  version: 1.0.0
  title: usergroup
basePath: /api
schemes:
- http

tags:
- name: UserGroup
  description: The UserGroup resource, accessed by its ID

paths:
  /userGroup:
    get:
      tags:
      - UserGroup
      description: Retrieves a list of the resource UserGroup filtered by query string.
      operationId: findUserGroup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: query
        name: filter
        type: string
        required: false
        description: The filter criteria for retrieving the list
      - in: query
        name: startIndex
        type: integer
        format: int32
        required: false
        description: The start index of the first element to return (page start)
      - in: query
        name: pageSize
        type: integer
        format: int32
        required: false
        description: Maximum number of items to return in requested page.  If the list is exausted, less elements will be returned.
      responses:
        200:
          description: requested page of items matching criteria.
          schema:
            $ref: "#/definitions/UserGroup"

    post:
      tags:
      - UserGroup
      description: Insert a new instance of the resource UserGroup.
      operationId: createUserGroup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: userGroup
        description: The entity data to update
        required: true
        schema:
          $ref: "#/definitions/UserGroup"
      responses:
        201:
          description: Created UserGroup resource.
          schema:
            $ref: "#/definitions/UserGroup"
        409:
          description: Entity with same ID already exists.
              
  /userGroup/{id}:
    get:
      tags:
      - UserGroup
      description: Retrieves an instance of the resource UserGroup, having the specified id.
      operationId: getUserGroup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: ID of the requested UserGroup instance
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Successful response, with a representation of the UserGroup resource.
          schema:
            $ref: "#/definitions/UserGroup"
          examples:
            application/json :
              {
                id : 1234,
                name : Weekly
              }
        404:
          description: The requested UserGroup resource instance was not found.

    post:
      tags:
      - UserGroup
      description: Updates an existing instance of the resource UserGroup, having the specified id.
      operationId: updateUserGroup
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: ID of the UserGroup instance to be updated
        required: true
        type: integer
        format: int64
      - in: body
        name: userGroup
        description: The entity data to update
        required: true
        schema:
          $ref: "#/definitions/UserGroup"
      responses:
        200:
          description: Successful response, with a representation of the UserGroup resource.
          schema:
            $ref: "#/definitions/UserGroup"
        404:
          description: The requested UserGroup resource instance was not found.
     
definitions:
  UserGroup:
    type: object
    description: An individual UserGroup resource instance.
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
