DROP TABLE IF EXISTS TBL_SHOPPING_LIST;

CREATE TABLE TBL_SHOPPING_LIST (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);

INSERT INTO TBL_SHOPPING_LIST (ID, NAME) VALUES
  (1, 'ShoppingList1'), (2, 'ShoppingList2'), (3, 'ShoppingList3');