DROP TABLE IF EXISTS TBL_GROUP_REF;

DROP SEQUENCE IF EXISTS SYSTEM_SEQUENCE_TBL_GROUP_REF;

CREATE SEQUENCE SYSTEM_SEQUENCE_TBL_GROUP_REF START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE TBL_GROUP_REF(
    GROUP_ID BIGINT DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_TBL_GROUP_REF) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_TBL_GROUP_REF,
    GROUP_NAME VARCHAR(255),
    FK_SHOPPINGLIST BIGINT NOT NULL
);
ALTER TABLE TBL_GROUP_REF ADD CONSTRAINT PK_TBL_GROUP_REF PRIMARY KEY(GROUP_ID);

DROP TABLE IF EXISTS TBL_LIST_ITEM;

DROP SEQUENCE IF EXISTS SYSTEM_SEQUENCE_TBL_LIST_ITEM;

CREATE SEQUENCE SYSTEM_SEQUENCE_TBL_LIST_ITEM START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE TBL_LIST_ITEM(
    ITEM_ID BIGINT DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_TBL_LIST_ITEM) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_TBL_LIST_ITEM,
    ITEM_DESCRIPTION VARCHAR(255),
    FK_SHOPPINGLIST BIGINT NOT NULL
);
ALTER TABLE TBL_LIST_ITEM ADD CONSTRAINT PK_TBL_LIST_ITEM PRIMARY KEY(ITEM_ID);

DROP TABLE IF EXISTS TBL_SHOPPING_LIST;

DROP SEQUENCE IF EXISTS SYSTEM_SEQUENCE_TBL_SHOPPING_LIST;

CREATE SEQUENCE SYSTEM_SEQUENCE_TBL_SHOPPING_LIST START WITH 1 BELONGS_TO_TABLE;

CREATE TABLE TBL_SHOPPING_LIST(
    ID BIGINT DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_TBL_SHOPPING_LIST) NOT NULL NULL_TO_DEFAULT SEQUENCE SYSTEM_SEQUENCE_TBL_SHOPPING_LIST,
    NAME VARCHAR(255)
);
ALTER TABLE TBL_SHOPPING_LIST ADD CONSTRAINT PK_TBL_SHOPPING_LIST PRIMARY KEY(ID);

ALTER TABLE TBL_GROUP_REF ADD CONSTRAINT FK_TBL_GROUP_REF_TBL_SHOPPING_LIST FOREIGN KEY(FK_SHOPPINGLIST) REFERENCES TBL_SHOPPING_LIST(ID) NOCHECK;
ALTER TABLE TBL_LIST_ITEM ADD CONSTRAINT FK_TBL_LIST_ITEM_TBL_SHOPPING_LIST FOREIGN KEY(FK_SHOPPINGLIST) REFERENCES TBL_SHOPPING_LIST(ID) NOCHECK;

INSERT INTO TBL_SHOPPING_LIST (ID, NAME) VALUES
  (1, 'ShoppingList1'), 
  (2, 'ShoppingList2'), 
  (3, 'ShoppingList3');